---
- name: DevOps
  hosts: localhost
  become: true

  tasks:
    - name: EDIT HOSTS
      blockinfile:
        path: /etc/hosts
        state: present
        content: |
          127.0.0.1 app.local api.local static.local

    # - name: RUNNING CREATE USER,
    #   ansible.builtin.shell: |
    #     bash ../../linux-admin/scripts/create_user.sh

    - name: GET GID
      ansible.builtin.shell: |
        getent group testusers | cut -d: -f3
      register: testusers_gid
      failed_when: testusers_gid.rc != 0

    - name: SET GID
      set_fact:
        testusers_gid_value: "{{ testusers_gid.stdout }}"

    - name: DEBUG GID
      debug:
        msg: "testusers GID: {{ testusers_gid_value }}"

    - name: RUNNING DOCKER COMPOSE
      community.docker.docker_compose_v2:
        project_src: "{{ playbook_dir }}/../.."
        build: "always"
        state: present
      environment:
        TESTUSERS_GID: "{{ testusers_gid.stdout }}"
